// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        button: string;
        generate: string;
        rightSide: string;
        title: string;
        topbarDaypicker: string;
        wrapper: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
