// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        body: string;
        bottomSide: string;
        container: string;
        cover: string;
        header: string;
        popper: string;
        row: string;
        topSide: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
