// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        cardBody: string;
        cardBodyHead: string;
        cardBtn: string;
        cardContainer: string;
        cardContent: string;
        cardHeader: string;
        cardItem: string;
        cardRow: string;
        cardSubRow: string;
        cardSubTitle: string;
        cardWrap: string;
        cardWrapper: string;
        chipContent: string;
        orderCardBody: string;
        orderCardChip: string;
        orderCardFooter: string;
        orderCardHeadSide: string;
        orderCardHeader: string;
        orderCardId: string;
        orderCardItem: string;
        orderCardRow: string;
        orderTable: string;
        orderTableActions: string;
        orderTableWrap: string;
        rightCard: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
