// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableModuleScssNamespace {
    export interface ITableModuleScss {
        bodyRow: string;
        container: string;
        inputData: string;
        table: string;
        tbody: string;
        td: string;
        th: string;
        thFirst: string;
        thRow: string;
        theader: string;
    }
}

declare const TableModuleScssModule: TableModuleScssNamespace.ITableModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableModuleScssNamespace.ITableModuleScss;
};

export = TableModuleScssModule;
