// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        activeCoefficient: string;
        activeKoefficientBtn: string;
        inactiveCoefficient: string;
        koefficientApproveBtn: string;
        koefficientBtn: string;
        koefficientHeaderTitle: string;
        koefficientResetBtn: string;
        parkKoefficient: string;
        parkKoefficientGray: string;
        parkKoefficientItems: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
