// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        add: string;
        addIcon: string;
        addModel: string;
        block: string;
        busIcon: string;
        busModel: string;
        models: string;
        noData: string;
        routeNumber: string;
        wrapper: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
