// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        activeText: string;
        addIcon: string;
        block: string;
        bottomContainer: string;
        bottomContainer2: string;
        content: string;
        contentBlock: string;
        formBtn: string;
        formField: string;
        formGroup: string;
        heading: string;
        input: string;
        inputRow: string;
        modal: string;
        parkContainer: string;
        subBlock: string;
        switchBlock: string;
        switchTitle: string;
        title: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
