#!/bin/sh

# The commit message passed as argument
commit_message_file="$1"

# Run your custom commit message checker (JavaScript)
node - <<EOF
const fs = require('fs');
const commit = fs.readFileSync("${commit_message_file}", 'utf-8').trim();

    const ticketNumberPattern = /^\[[a-zA-Zа-яА-Я0-9_]+-\d+\]/;
    const branchTypePattern = /\]\s+(feat|fix|hotfix|rel)\b\s+\(/i;
    const descriptionPattern = /\(.{4,88}\)$/;
    const template = '[ABS-123] feat (Description)'

    if(!ticketNumberPattern.test(commit)){
        console.error('Error: Ticket number must match the pattern [prefix-number]');
        console.log('Template:', template);
        process.exit(1);
    }
    if(!branchTypePattern.test(commit)){
        console.error('Error: Branch type must match the pattern "feat" | "fix" | "hotfix" | "rel"');
        console.log('Template:', template);
        process.exit(1);
    }
    if(!descriptionPattern.test(commit)){
        console.error('Error: Description must have a length between 4 and 88 characters');
        console.log('Template:', template);
        process.exit(1);
    }
EOF